migrations and fixtures, add reload binary

diff --git a/src/AppBundle/Resources/bin/archive b/src/AppBundle/Resources/bin/archive
--- a/src/AppBundle/Resources/bin/archive
+++ b/src/AppBundle/Resources/bin/archive
@@ -1,19 +1,19 @@
 #!/bin/sh
 
 DIR="$( cd "$( dirname "$0" )" && pwd )"
+DIR="$( dirname "$DIR" )"
+PWD="$(pwd)"
 
-LOCATION="$1"
-if [ !-d "$LOCATION" ]; then
-    echo "A valid file directory location is required as first argument." && exit 1
+cd $DIR
+
+PACKAGE="$1"
+if [ ! -d "$(dirname "$PACKAGE")" ]; then
+    echo "A valid file directory location is required as first argument."
+    exit 1
 fi
 
-NAME="$2"
-if [ -z "$NAME" ]; then
-    NAME="app"
-fi
-LOCATION="${LOCATION}/${NAME}.tar.gz"
+tar --exclude-from=.tarignore --exclude-vcs -czf $PACKAGE .
 
-tar --exclude-from=$DIR/../.tarignore --exclude-vcs -czf $LOCATION $DIR/..
+echo "Have archived application to $PACKAGE"
 
-echo "Have archived application to $LOCATION"
-
+cd $PWD # go back
